import React, { useState, useRef, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import StockChart from './StockChart';
import '../styles/IrisChatbot.css';

const IrisChatbot = () => {
  const { isLoggedIn, user } = useAuth();
  const [query, setQuery] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [responseData, setResponseData] = useState(null);
  const [chatHistory, setChatHistory] = useState([]);
  const [activeTab, setActiveTab] = useState('chat'); // 'chat' or 'history'
  const responseRef = useRef(null);

  const categories = [
    {
      id: 'market-explorer',
      title: 'Market Explorer',
      icon: '🔍',
      description: 'Search & Analyze',
      items: ['Screener', 'IPO', 'ETF', 'Bulk/Block Deals', 'Market Movers'],
    },
    {
      id: 'market-pulse',
      title: 'Market Pulse',
      icon: '📊',
      description: 'Live Updates',
      items: ['Market', 'FII DII Activity', 'Corporate Actions', 'Articles', 'Daily Updates'],
    },
    {
      id: 'deep-dive',
      title: 'Deep Dive',
      icon: '🔬',
      description: 'In-Depth Analysis',
      items: ['Earnings Tracker', 'All Sectors', 'All Industries', 'Sector Analysis'],
    },
    {
      id: 'investors-suite',
      title: "Investor's Suite",
      icon: '💼',
      description: 'Personal Tools',
      items: ['Dashboard', 'Portfolio', 'Timeline', 'Discovery', 'Watchlists'],
    },
  ];

  const fetchingStages = [
    { stage: 'Parsing', icon: '📝' },
    { stage: 'Scanning', icon: '🔎' },
    { stage: 'Fetching', icon: '⬇️' },
    { stage: 'Gathering data', icon: '📦' },
  ];

  const handleQuerySubmit = async (e) => {
    e.preventDefault();
    if (!query.trim()) {
      alert('Please enter a query!');
      return;
    }

    // Add to chat history
    const newMessage = { type: 'user', content: query, timestamp: new Date() };
    setChatHistory([...chatHistory, newMessage]);

    setIsLoading(true);
    setQuery('');

    // Simulate API call with fetching stages
    try {
      // Simulate fetching stages
      const stages = [];
      for (let i = 0; i < fetchingStages.length; i++) {
        await new Promise((resolve) => setTimeout(resolve, 600));
        stages.push(fetchingStages[i]);
      }

      // Simulate response data (placeholder)
      const mockResponse = {
        query,
        stages,
        sources: {
          database: ['Stock Fundamentals', 'Historical Data'],
          files: ['Annual Reports', 'Quarterly Statements'],
          documents: ['Market Analysis', 'News Articles'],
        },
        analysis: {
          title: `Analysis for: ${query}`,
          summary: 'This is a placeholder response. The actual analysis will be generated by the backend API.',
          whatStandsOut: [
            'Strong fundamental performance',
            'Consistent revenue growth',
            'Improving profit margins',
          ],
          businessModel: 'B2B SaaS platform with recurring revenue',
          recommendation: 'Hold',
          confidenceLevel: 78,
        },
        metrics: {
          peRatio: 24.5,
          dividendYield: 2.3,
          debtToEquity: 0.45,
          roe: 18.2,
        },
      };

      setChatHistory((prev) => [
        ...prev,
        { type: 'bot', content: mockResponse, timestamp: new Date() },
      ]);
      setResponseData(mockResponse);
    } catch (error) {
      console.error('Error fetching response:', error);
      setChatHistory((prev) => [
        ...prev,
        {
          type: 'bot',
          content: { error: 'Failed to fetch response. Please try again.' },
          timestamp: new Date(),
        },
      ]);
    } finally {
      setIsLoading(false);
    }

    // Scroll to response
    setTimeout(() => {
      if (responseRef.current) {
        responseRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }, 100);
  };

  const handleCategoryClick = (items) => {
    const itemsText = items.join(', ');
    setQuery(`Show me ${itemsText}`);
  };

  const clearHistory = () => {
    setChatHistory([]);
    setResponseData(null);
  };

  return (
    <div className="iris-chatbot-container">
      <div className="iris-layout">
        {/* Sidebar - Chat History */}
        <aside className="iris-sidebar">
          <div className="sidebar-header">
            <h3>Chat History</h3>
            {chatHistory.length > 0 && (
              <button className="clear-btn" onClick={clearHistory} title="Clear history">
                🗑️
              </button>
            )}
          </div>

          {chatHistory.length === 0 ? (
            <div className="sidebar-empty">
              <p>No chat history yet</p>
              <p className="sidebar-hint">Start a conversation to see history here</p>
            </div>
          ) : (
            <div className="chat-history-list">
              {chatHistory
                .filter((msg) => msg.type === 'user')
                .map((msg, idx) => (
                  <div
                    key={idx}
                    className="history-item"
                    onClick={() => setQuery(msg.content)}
                    title={msg.content}
                  >
                    <span className="history-icon">💬</span>
                    <span className="history-text">
                      {msg.content.substring(0, 30)}
                      {msg.content.length > 30 ? '...' : ''}
                    </span>
                  </div>
                ))}
            </div>
          )}
        </aside>

        {/* Main Content Area */}
        <main className="iris-main">
          {/* Header Section */}
          {chatHistory.length === 0 ? (
            <div className="iris-hero">
              <div className="iris-header">
                <h1 className="iris-title">Ask Iris</h1>
                <p className="iris-subtitle">AI-powered stock research & market insights</p>
              </div>

              {/* Quick Action Categories */}
              <div className="categories-grid">
                {categories.map((category) => (
                  <div
                    key={category.id}
                    className="category-card"
                    onClick={() => handleCategoryClick(category.items)}
                  >
                    <div className="category-header">
                      <span className="category-icon">{category.icon}</span>
                      <h3>{category.title}</h3>
                    </div>
                    <p className="category-description">{category.description}</p>
                    <div className="category-items">
                      {category.items.map((item, idx) => (
                        <span key={idx} className="category-item">
                          {item}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="chat-area">
              {/* Chat Messages */}
              <div className="chat-messages">
                {chatHistory.map((msg, idx) => (
                  <div key={idx} className={`message-wrapper ${msg.type}`}>
                    {msg.type === 'user' ? (
                      <div className="user-message">
                        <div className="message-content">{msg.content}</div>
                      </div>
                    ) : msg.content.error ? (
                      <div className="bot-message error">
                        <div className="message-content">{msg.content.error}</div>
                      </div>
                    ) : (
                      <div className="bot-message">
                        <ResponseDisplay data={msg.content} />
                      </div>
                    )}
                  </div>
                ))}

                {isLoading && (
                  <div className="message-wrapper bot loading">
                    <div className="bot-message">
                      <FetchingIndicator stages={fetchingStages} />
                    </div>
                  </div>
                )}

                <div ref={responseRef} />
              </div>
            </div>
          )}

          {/* Input Area */}
          <div className="iris-input-area">
            <form onSubmit={handleQuerySubmit} className="iris-form">
              <div className="input-wrapper">
                <input
                  type="text"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Ask Iris anything about stocks, markets, or your portfolio..."
                  className="iris-input"
                  disabled={isLoading}
                />
                <button
                  type="submit"
                  className="send-btn"
                  disabled={isLoading || !query.trim()}
                  title="Send query"
                >
                  {isLoading ? '⏳' : '➤'}
                </button>
              </div>
              <p className="input-hint">
                {isLoggedIn ? `Logged in as ${user?.username || 'User'}` : 'Login to save your queries'}
              </p>
            </form>
          </div>
        </main>
      </div>
    </div>
  );
};

// Fetching Indicator Component
const FetchingIndicator = ({ stages }) => {
  const [displayedStages, setDisplayedStages] = useState([]);

  useEffect(() => {
    setDisplayedStages(stages);
  }, [stages]);

  return (
    <div className="fetching-indicator">
      <div className="fetching-timeline">
        {stages.map((stage, idx) => (
          <div key={idx} className="timeline-stage">
            <div className={`stage-dot ${idx < displayedStages.length ? 'completed' : ''}`}>
              {idx < displayedStages.length ? '✓' : '○'}
            </div>
            <div className="stage-label">{stage.stage}</div>
          </div>
        ))}
      </div>
      <div className="fetching-status">
        <span className="spinner"></span>
        <span>Gathering insights...</span>
      </div>
    </div>
  );
};

// Response Display Component
const ResponseDisplay = ({ data }) => {
  const [expandedSection, setExpandedSection] = useState('summary');

  return (
    <div className="response-display">
      {/* Sources Section */}
      <div className="sources-section">
        <h4>Data Sources</h4>
        <div className="sources-grid">
          {data.sources.database && (
            <div className="source-item">
              <span className="source-icon">🗄️</span>
              <div className="source-content">
                <span className="source-type">Database</span>
                {data.sources.database.map((item, idx) => (
                  <div key={idx} className="source-item-text">{item}</div>
                ))}
              </div>
            </div>
          )}
          {data.sources.files && (
            <div className="source-item">
              <span className="source-icon">📄</span>
              <div className="source-content">
                <span className="source-type">Files</span>
                {data.sources.files.map((item, idx) => (
                  <div key={idx} className="source-item-text">{item}</div>
                ))}
              </div>
            </div>
          )}
          {data.sources.documents && (
            <div className="source-item">
              <span className="source-icon">📃</span>
              <div className="source-content">
                <span className="source-type">Documents</span>
                {data.sources.documents.map((item, idx) => (
                  <div key={idx} className="source-item-text">{item}</div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Fetching Timeline */}
      <div className="response-timeline">
        <h4>Analysis Timeline</h4>
        <div className="timeline-horizontal">
          {data.stages.map((stage, idx) => (
            <div key={idx} className="timeline-step completed">
              <div className="step-marker">✓</div>
              <div className="step-label">{stage.stage}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Analysis Content */}
      <div className="analysis-section">
        <h4>{data.analysis.title}</h4>

        {/* Summary */}
        <div className="analysis-item">
          <button
            className="analysis-toggle"
            onClick={() =>
              setExpandedSection(expandedSection === 'summary' ? null : 'summary')
            }
          >
            <span className="toggle-icon">
              {expandedSection === 'summary' ? '▼' : '▶'}
            </span>
            Summary
          </button>
          {expandedSection === 'summary' && (
            <div className="analysis-content">{data.analysis.summary}</div>
          )}
        </div>

        {/* What Stands Out */}
        <div className="analysis-item">
          <button
            className="analysis-toggle"
            onClick={() =>
              setExpandedSection(expandedSection === 'standsout' ? null : 'standsout')
            }
          >
            <span className="toggle-icon">
              {expandedSection === 'standsout' ? '▼' : '▶'}
            </span>
            What Stands Out
          </button>
          {expandedSection === 'standsout' && (
            <div className="analysis-content">
              <ul>
                {data.analysis.whatStandsOut.map((point, idx) => (
                  <li key={idx}>{point}</li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Business Model */}
        <div className="analysis-item">
          <button
            className="analysis-toggle"
            onClick={() =>
              setExpandedSection(expandedSection === 'business' ? null : 'business')
            }
          >
            <span className="toggle-icon">
              {expandedSection === 'business' ? '▼' : '▶'}
            </span>
            Business Model
          </button>
          {expandedSection === 'business' && (
            <div className="analysis-content">{data.analysis.businessModel}</div>
          )}
        </div>

        {/* Metrics */}
        <div className="metrics-section">
          <h5>Key Metrics</h5>
          <div className="metrics-grid">
            <div className="metric-card">
              <div className="metric-label">P/E Ratio</div>
              <div className="metric-value">{data.metrics.peRatio}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Dividend Yield</div>
              <div className="metric-value">{data.metrics.dividendYield}%</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">Debt to Equity</div>
              <div className="metric-value">{data.metrics.debtToEquity}</div>
            </div>
            <div className="metric-card">
              <div className="metric-label">ROE</div>
              <div className="metric-value">{data.metrics.roe}%</div>
            </div>
          </div>
        </div>

        {/* Recommendation */}
        <div className="recommendation-section">
          <div className={`recommendation ${data.analysis.recommendation.toLowerCase()}`}>
            <span className="rec-label">Recommendation:</span>
            <span className="rec-value">{data.analysis.recommendation}</span>
            <span className="rec-confidence">
              Confidence: {data.analysis.confidenceLevel}%
            </span>
          </div>
        </div>

        {/* Stock Chart */}
        <div className="chart-section">
          <StockChart
            stockSymbol={data.query.toUpperCase()}
            stockName={data.query}
          />
        </div>
      </div>
    </div>
  );
};

export default IrisChatbot;
